#!/bin/bash
#PBS -N nspe_7_2_fep_test.pf
#PBS -o nspe_7_2_fep_test.out
#PBS -q normal
#PBS -l nodes=1:ppn=28
#PBS -l walltime=48:00:00
#PBS -M tur54445@temple.edu  
#PBS -m bae
cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=1

# Load the necessary modules
module load gromacs/2021.2
module load mpi/openmpi

# Define the state directories for the multidir flag
state_dirs=$(echo state_{0..3} | tr ' ' ' ')

# Run the GROMACS mdrun with MPI
mpirun -np 16 mdrun_mpi -deffnm HREMD -dhdl dhdl.xvg -replex 5000 -multidir $state_dirs -noappend
