#!/bin/bash
#PBS -N nspe_10_fep_test.pf
#PBS -o nspe_10_fep_test.out
#PBS -q big
#PBS -l nodes=1:ppn=32
#PBS -l walltime=48:00:00
#PBS -M tur54445@temple.edu  
#PBS -m bae
cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=1

# Load the necessary modules
module load gromacs/2021.2
module load mpi/openmpi

# Define the state directories for the multidir flag
state_dirs=$(echo state_{0..7} | tr ' ' ' ')

# Run the GROMACS mdrun with MPI
mpirun -np 8 mdrun_mpi -deffnm HREMD -dhdl dhdl.xvg -replex 5000 -multidir $state_dirs -noappend
