#!/bin/bash
#PBS -N nspe_7_1_remd.pf
#PBS -o nspe_7_1_remd_test.out
#PBS -q normal
#PBS -l nodes=4:ppn=24
#PBS -l walltime=48:00:00
#PBS -M tur54445@temple.edu  
#PBS -m bae
cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=1

# Load the necessary modules
module load gromacs/2021.2
module load mpi/openmpi

# Define the state directories for the multidir flag
state_dirs=$(echo state_{0..15} | tr ' ' ' ')

# Run the GROMACS mdrun with MPI
mpirun -np 96 mdrun_mpi -deffnm HREMD -dhdl dhdl.xvg -replex 500 -multidir $state_dirs -noappend


