#!/bin/bash

# Load GROMACS module
# module load gromacs/2021.2
#sed -i '' 's/nspe_7_1/nspe_10/g' runme 

# make an peptoid.itp file 
mv nspe_10_GMX.top nspe_10.itp

#make a new top file 
# adding the following solvent atomtype in peptoid.itp:
#[atomtypes]

cat >> nspe_10.top  <<EOL

[ defaults ]
; nbfunc        comb-rule       gen-pairs       fudgeLJ fudgeQQ
1               2               yes             0.5          0.83333333    

; Include Peptoid
#include "./nspe_10.itp"

; Include chloroform model
#include "./chloroform_320_box.itp"

; Include Ion
;#include "amber03.ff/ions.itp"

[ system ]
 nspe_10

[ molecules ]
; Compound        nmols
 nspe_10          1

EOL




# Add a box
gmx editconf -f nspe_10_GMX.gro -o nspe_10_boxed.gro -c -d 1 -bt cubic

# Make an solvated top file
cp nspe_10.top nspe_10_sol.top

# Solvate the molecule with water
gmx solvate -cp nspe_10_boxed.gro -cs chloroform_320_box.gro -o nspe_10_sol.gro -p nspe_10_sol.top

 Make an index file for our solvated+neutralized  peptoid
echo "\!4\nname 16 peptoid\nq\n" | gmx make_ndx -f nspe_10_sol.gro -o index.ndx 
echo "q" | gmx make_ndx -n index.ndx 
#234

# Prepare a EM.tpr file
gmx grompp -f mdp/em.mdp -c nspe_10_sol.gro -p nspe_10_sol.top -n index.ndx -o em_sol.tpr -maxwarn 1

#Run the EM 
gmx mdrun -nt 1 -v -s em_sol.tpr -c em_sol.gro -o em_sol.trr

# Prepare a NVT.tpr file
gmx grompp -f mdp/nvt.mdp -c em_sol.gro -p nspe_10_sol.top -n index.ndx -o nvt_sol.tpr -maxwarn 1
#Run the NVT 
gmx mdrun -nt 1 -v -s nvt_sol.tpr -c nvt_sol.gro -o nvt_sol.trr

# Check the run 
echo "16\n0\n" |gmx energy -f ener.edr -o temperature.xvg

# Prepare a NPT.tpr file
gmx grompp -f mdp/npt.mdp -c nvt_sol.gro -p nspe_10_sol.top -n index.ndx  -o npt_sol.tpr -maxwarn 1
#Run the NPT 
gmx mdrun -nt 1 -v -s npt_sol.tpr -c npt_sol.gro -o npt_sol.trr 

# Check the run 
echo "18\n0\n" |gmx energy -f ener.edr -o temperature.xvg
